package net.neoforged.meta.extract;

import org.jspecify.annotations.Nullable;

import java.nio.charset.StandardCharsets;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Given a changelog generated by gradleutils, try to extract a nice entry for just a single version.
 */
public final class ChangelogExtractor {
    private ChangelogExtractor() {
    }

    @Nullable
    public static String extract(byte[] changelogBody) {
        String[] lines = new String(changelogBody, StandardCharsets.UTF_8).split("\n");
        for (int i = 0; i < lines.length; i++) {
            var line = lines[i];
            Pattern startOfChangelogPattern = Pattern.compile("^ - `[^`]+` ");
            Matcher matcher = startOfChangelogPattern.matcher(line);
            if (matcher.find()) {
                line = line.replace("\r", "");
                // Found the version, now scan all
                var versionEntry = new StringBuilder();
                versionEntry.append(line.substring(matcher.group().length()));
                // Append any continuation lines.
                for (int j = i + 1; j < lines.length; j++) {
                    var continuationLine = lines[j];
                    if (continuationLine.startsWith("   ")) {
                        continuationLine = continuationLine.replace("\r", "");
                        versionEntry.append('\n').append(continuationLine.substring(3));
                    } else break;
                }

                return versionEntry.toString();
            }
        }

        return null;
    }
}
